## Implementação da Regressão Linear ##

Este notebook apenas trás como implementar a Regressão Linear no Stats e no Sckit_Learn 
Nao tem nenhum tratamento nos dados que utilizamos para a implementação.

In [2]:
import pandas as pd 
import numpy as np
import statsmodels.api as sm

In [11]:
data = pd.read_csv('housing.csv')

In [12]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

### StatsModel ###

In [14]:
y= 'median_house_value'

In [15]:
data_dropped=data.drop([y],axis=1) #retira a variável target(y)

In [16]:
#porcentagem de NANs
data.isna().sum()/data.shape[0]

longitude             0.000000
latitude              0.000000
housing_median_age    0.000000
total_rooms           0.000000
total_bedrooms        0.010029
population            0.000000
households            0.000000
median_income         0.000000
median_house_value    0.000000
ocean_proximity       0.000000
dtype: float64

Como a idéia aqui é rodar o modelo, vamos dropar o que tiver total_bedrooms zerado para conseguir rodar a regressão

In [17]:
#transforma dados categóricos em dummies para o modelo e dropa os valores nulos
data_dropped.dropna(inplace=True)
data_dummies=pd.get_dummies(data_dropped)

In [21]:
modelo = sm.OLS(np.array(data[y]), data_dummies)
res=modelo.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.646
Model:                            OLS   Adj. R-squared:                  0.646
Method:                 Least Squares   F-statistic:                     3112.
Date:                Thu, 02 Mar 2023   Prob (F-statistic):               0.00
Time:                        18:04:26   Log-Likelihood:            -2.5655e+05
No. Observations:               20433   AIC:                         5.131e+05
Df Residuals:                   20420   BIC:                         5.132e+05
Df Model:                          12
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
longitude                  -2.681e+04   1019.651    -26.296      0.000   -2.88e+04   -2.48e+04
latitude                   -2.548e+04   1004.702    -25.363      0.000   -2.75e+04   -2.35e+04
housing_median_age          1072.5200     43.886     24.439      0.000     986.501    1158.540
total_rooms                   -6.1933      0.791     -7.825      0.000      -7.745      -4.642
total_bedrooms               100.5563      6.869     14.640      0.000      87.093     114.019
population                   -37.9691      1.076    -35.282      0.000     -40.078     -35.860
households                    49.6173      7.451      6.659      0.000      35.012      64.222
median_income               3.926e+04    338.005    116.151      0.000    3.86e+04    3.99e+04
ocean_proximity_<1H OCEAN   -2.27e+06    8.8e+04    -25.791      0.000   -2.44e+06    -2.1e+06
ocean_proximity_INLAND     -2.309e+06    8.7e+04    -26.545      0.000   -2.48e+06   -2.14e+06
ocean_proximity_ISLAND     -2.117e+06   9.39e+04    -22.536      0.000    -2.3e+06   -1.93e+06
ocean_proximity_NEAR BAY   -2.274e+06   8.85e+04    -25.707      0.000   -2.45e+06    -2.1e+06
ocean_proximity_NEAR OCEAN -2.266e+06   8.84e+04    -25.640      0.000   -2.44e+06   -2.09e+06
==============================================================================
Omnibus:                     5049.292   Durbin-Watson:                   0.977
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            19123.138
Skew:                           1.197   Prob(JB):                         0.00
Kurtosis:                       7.090   Cond. No.                     1.62e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.62e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [26]:
#normalizando
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=data_dummies
normalized_x = scaler.fit_transform(x)
normalized_x= pd.DataFrame(normalized_x, columns=x.columns)

modelo = sm.OLS(np.array(data[y]), normalized_x)
res=modelo.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.153
Model:                            OLS   Adj. R-squared (uncentered):              0.153
Method:                 Least Squares   F-statistic:                              308.6
Date:                Fri, 03 Mar 2023   Prob (F-statistic):                        0.00
Time:                        10:38:32   Log-Likelihood:                     -2.8016e+05
No. Observations:               20433   AIC:                                  5.603e+05
Df Residuals:                   20421   BIC:                                  5.604e+05
Df Model:                          12
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
longitude                  -5.372e+04   6487.145     -8.281      0.000   -6.64e+04    -4.1e+04
latitude                   -5.444e+04   6815.616     -7.987      0.000   -6.78e+04   -4.11e+04
housing_median_age           1.35e+04   1754.717      7.696      0.000    1.01e+04    1.69e+04
total_rooms                -1.353e+04   5492.058     -2.464      0.014   -2.43e+04   -2768.746
total_bedrooms              4.237e+04   9190.465      4.610      0.000    2.44e+04    6.04e+04
population                 -4.303e+04   3872.378    -11.111      0.000   -5.06e+04   -3.54e+04
households                  1.897e+04   9045.489      2.097      0.036    1238.317    3.67e+04
median_income               7.456e+04   2038.498     36.578      0.000    7.06e+04    7.86e+04
ocean_proximity_<1H OCEAN   6178.6502   1198.107      5.157      0.000    3830.264    8527.037
ocean_proximity_INLAND      -1.25e+04   1754.538     -7.124      0.000   -1.59e+04   -9061.045
ocean_proximity_ISLAND      2586.1352   1526.591      1.694      0.090    -406.105    5578.375
ocean_proximity_NEAR BAY    2666.9925   1588.723      1.679      0.093    -447.031    5781.016
ocean_proximity_NEAR OCEAN  5597.1006   1455.650      3.845      0.000    2743.910    8450.292
==============================================================================
Omnibus:                     5049.292   Durbin-Watson:                   0.097
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            19123.138
Skew:                           1.197   Prob(JB):                         0.00
Kurtosis:                       7.090   Cond. No.                     1.14e+16
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 6.16e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

### Sckit-learn

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [38]:
xtrain,xval,ytrain,yval = train_test_split(x,data[y],test_size=0.3, random_state=0)
print(xtrain.shape, xval.shape,ytrain.shape, yval.shape)

modelo=LinearRegression()
modelo.fit(xtrain,ytrain)

p=modelo.predict(xval)

(14303, 13) (6130, 13) (14303,) (6130,)

In [39]:
from sklearn.metrics import mean_squared_error
mean_squared_error(yval,p)

4699359207.200234